@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-head"><div><span class="eyebrow">WORKSPACE OVERVIEW</span><h1>{{ $site?->name ?? $workspace->name }}</h1><p>Track publishing health, AI usage and the next opportunities worth acting on.</p></div><div class="toolbar"><a class="btn secondary" href="{{ route('app.content.index') }}">Open content</a><form method="post" action="{{ route('app.automation.run') }}">@csrf<button class="btn">Run evolution</button></form></div></div>
<div class="stats"><div class="stat"><span>Published pages</span><strong>{{ $stats['published'] }}</strong></div><div class="stat"><span>Draft / review</span><strong>{{ $stats['drafts'] }}</strong></div><div class="stat"><span>Average health</span><strong>{{ $stats['avg_health'] }}<small style="font-size:14px;color:#8897aa">/100</small></strong></div><div class="stat"><span>AI actions this month</span><strong>{{ $stats['actions_this_month'] }}</strong></div></div>
<div class="grid-2">
<section class="panel"><div class="panel-head"><h2>Usage this month</h2><span class="pill">{{ ucfirst($workspace->plan) }}</span></div>@foreach(['ai_generations'=>'AI generations','ai_improvements'=>'AI improvements','evolution_runs'=>'Evolution runs'] as $meter=>$label)@php($limit=(int)data_get($plan,'limits.'.$meter,0))@php($used=(int)($usage[$meter]??0))<div style="margin:17px 0"><div class="kpi-row"><span>{{ $label }}</span><strong>{{ $used }} / {{ $limit ?: '∞' }}</strong></div>@if($limit)<div class="meter"><span style="width:{{ min(100,round(($used/max(1,$limit))*100)) }}%"></span></div>@endif</div>@endforeach @if($workspace->isTrialing())<div class="notice">Trial active until <strong>{{ optional($workspace->trial_ends_at)->format('M j, Y') }}</strong>. <a href="{{ route('app.billing') }}" style="color:#b8adff">Choose a plan →</a></div>@elseif(!$workspace->subscriptionActive())<div class="flash error">Your trial/subscription is inactive. AI automation is paused until billing is active.</div>@endif</section>
<section class="panel"><div class="panel-head"><h2>Sites</h2><a href="{{ route('app.sites') }}" class="btn ghost small">Manage</a></div><div class="stack">@forelse($sites as $s)@php($publicUrl=$s->domain ? 'https://'.$s->domain : route('public.site',['workspace'=>$workspace->slug,'site'=>$s->slug]))<div class="site-card {{ $site && $site->id===$s->id?'active':'' }}"><div class="panel-head" style="margin:0"><div><strong>{{ $s->name }}</strong><div class="muted" style="font-size:12px">{{ $s->domain ?: 'Hosted: '.$publicUrl }}</div><a href="{{ $publicUrl }}" target="_blank" style="font-size:12px;color:#b8adff">Open site ↗</a></div>@if(!$site || $site->id!==$s->id)<form method="post" action="{{ route('app.sites.switch',$s) }}">@csrf<button class="btn ghost small">Switch</button></form>@else<span class="pill green">Active</span>@endif</div></div>@empty<div class="empty">No sites yet.</div>@endforelse</div></section>
</div>
<div class="grid-2">
<section class="panel"><div class="panel-head"><h2>Recent AI activity</h2><a href="{{ route('app.automation') }}" class="btn ghost small">View all</a></div><div class="table-wrap"><table><thead><tr><th>Action</th><th>Status</th><th>When</th></tr></thead><tbody>@forelse($recentActions as $action)<tr><td><strong>{{ str_replace('_',' ',ucfirst($action->action_type)) }}</strong><div class="muted">{{ \Illuminate\Support\Str::limit($action->summary,90) }}</div></td><td><span class="pill {{ $action->status==='failed'?'red':($action->status==='completed'?'green':'yellow') }}">{{ $action->status }}</span></td><td>{{ $action->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="3" class="empty">No AI activity yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-head"><h2>Top opportunities</h2><a href="{{ route('app.opportunities') }}" class="btn ghost small">View all</a></div>@forelse($opportunities as $op)<div class="kpi-row"><div><strong>{{ $op->topic }}</strong><div class="muted" style="font-size:12px">{{ \Illuminate\Support\Str::limit($op->reason,105) }}</div></div><span class="pill">{{ $op->priority }}/100</span></div>@empty<div class="empty">Run opportunity discovery to populate this queue.</div>@endforelse</section>
</div>
@endsection